config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: "blog#home"

  get "blog/:slug" => "blog#show", as: :show_page

  %w(about).each do |page|
    get page, to: "blog##{page}", as: page
  end
  namespace :admin do
    root to: "pages#index"

    resources :pages, only: [:create, :index, :new, :edit, :update, :destroy]
    resources :images, only: [:index, :create]
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

end

app/models/image.rb
class Image < ActiveRecord::Base

  OPTIONS_FOR_URL = {
    thumb: {size: "190x190", crop: "thumb" }
  }

  has_attachment :attachment, accept: [:png, :jpg, :jpeg, :gif]

  validates :attachment, presence: true

  delegate :width, :height, to: :attachment

  def url(**options)
    Cloudinary::Utils.cloudinary_url(attachment.path, options)
  end

  def url_for(key)
    options = OPTIONS_FOR_URL.fetch(key)
    url(options)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_attachment :image, accept: [:jpg, :png, :gif, :jpeg]

  validates :image, presence: true

  validates :title, presence: true
  validates :short_description, presence: true
  validates :body, presence: true
  validates :slug, presence: true

  scope :published, -> { where(published: true) }

  before_validation :generate_slug!

  private

  def generate_slug!
    return if slug.present?
    self.slug = title.parameterize
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout "admin"

  before_action :authenticate_admin!

  private

  def authenticate_admin!
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV.fetch("ADMIN_USERNAME") && password == ENV.fetch("ADMIN_PASSWORD")
    end
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def index
    @images = Image.order("created_at DESC").page(params[:page]).per_page(8)
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      render status: :created
    else
      render status: :bad_request
    end
  end

  private

  def image_params
    params.require(:image).permit(:attachment)
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController

  def index
    @pages = Page.all.order("created_at DESC")
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to admin_root_path, notice: "Article created!"
    else
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to admin_root_path, notice: "Changes saved successfully!"
    else
      render 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    redirect_to admin_root_path
  end


  private

  def page_params
    params.require(:page).permit(:title, :image, :short_description, :body, :slug, :published)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def home
    @pages = Page.all.order("created_at DESC").page(params[:page]).per_page(6)
  end

  def show
    @page = Page.find_by_slug(params[:slug])
  end

  def about

  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper

  def human_name_for_boolean(boolean)
    boolean ? "YES" : "NO"
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
  PAGE_IMAGE_OPTIONS = {
    small: { width: 20, height: 20 },
    no_image: { width: 0, height: 0 },
    large: { width: 990, height: 400, class: "image" }
  }

  def page_image_tag(page, size)
    image_path = page_image_path(page, size)
    options = PAGE_IMAGE_OPTIONS[size]
    cl_image_tag(image_path, options)
  end

  def page_image_path(page, size)
    if page.image.present?
      page.image.path
    else
      nil
    end
  end

  def admin_menu_items
    [
      ["Home", admin_root_path],
      ["New article", new_admin_page_path],
      ["Blog", root_path]
    ]
  end

  def render_admin_menu
    items = admin_menu_items
    return "" if items.empty?
    lis = items.map do |item|
      li_class = current_page?(item[1]) ? "active" : nil
      content_tag(:li, link_to(item[0], item[1]), class: li_class)
    end
    content_tag(:ul, lis.join("").html_safe, class: "admin-nav pull-right")
  end

  def render_flash_messages
    msg = nil
    class_name = nil
    [:notice, :success, :alert].each do |key|
      next if flash[key].blank?
      msg = flash[key]
      class_name = key
      class_name = :success if %w(notice success).include?(key.to_s)
      break
    end
    return if msg.blank?
    close_link = link_to("x", "#", class: "close")
    msg.blank? ? "" : content_tag(:div, "#{close_link}#{msg}".html_safe, :class => "alert alert-#{class_name}", "data-dismiss" => "alert")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper

  def link_to_blog(page, text: nil)
    text ||= page.title
    link_to text, "/blog/#{page.slug}"
  end

  def main_menu_items
    [
      ["Home", root_path],
      ["About", about_path]
    ]
  end

  def render_main_menu
    items = main_menu_items
    return "" if items.empty?
    lis = items.map do |item|
      li_class = current_page?(item[1]) ? "active" : nil
      content_tag(:li, link_to(item[0], item[1]), class: li_class)
    end
    content_tag(:ul, lis.join("").html_safe, class: "navigation")
  end

  def md_to_html(text)
    options = {
      hard_wrap: true,
      fenced_code_blocks: true,
      gh_blockcode: true
    }
    extensions = {
      autolink: true,
      no_intra_emphasis: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    md_for_html= Redcarpet::Markdown.new(renderer, extensions)
    md_for_html.render(text).html_safe
  end

end

app/views/admin/images/index.html.erb
<% if @images.any? %>

  <div class="row">
    <% @images.each do |image| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to(
            image_tag(image.url_for(:thumb)),
            image.url,
            target: "_blank"
          ) %>
        <span class="label label-default">
          <%= image.width %>x<%= image.height %>px
        </span>
        <button class="btn btn-default btn-xs pull-right choose-image">Odaberi</button>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @images, renderer: BootstrapPagination::Rails %>

  <% else %>

    <p class="well">No images found</p>

  <% end %>

app/views/admin/pages/_form.html.erb
<%= f.input :title %>
<%= f.input :image, as: :attachinary %>
<%= f.input :short_description, input_html: { rows: 5 } %>

<%= f.input :body do %>
  <%= f.input_field :body, class: "form-control", rows: 20 %>
  <%= link_to "Markdown help", "http://assemble.io/docs/Cheatsheet-Markdown.html", target: "_blank", class: "pull-right" %>
  <%= link_to "Add new image", "#new-image-modal", data: { toggle: "modal" } %> |
  <%= link_to "Use image from gallery", "#images-modal", data: { toggle: "modal" } %>
<% end %>

<% if f.object.persisted? %>
  <%= f.input :slug %>
<% end %>

<%= f.input :published %>

app/views/admin/pages/edit.html.erb
<% provide(:title, "Edit Article") %>

<%= render "admin/pages/modals/new_image" %>
<%= render "admin/pages/modals/images" %>

<div class="form-wrapper">
  <h1>New Article</h1>

  <%= simple_form_for [:admin, @page] do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "Create new article", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/pages/index.html.erb
<% provide(:title, "Home") %>
<div class="index-wrapper">
  <table class="table table-action">
    <thead>
      <tr>
        <th class="t-small">Title</th>
        <th class="t-medium">Slug</th>
        <th class="t-small">Cover image</th>
        <th class="t-medium">Date</th>
        <th class="t-smass">Published</th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= link_to page.title, edit_admin_page_path(page) %></td>
          <td><%= page.slug %></td>
          <td><% if page.image.present? %>
            <%= page_image_tag(page, :small) %>
          <% else %>
            <%= page_image_tag(page, :no_image) %>
          <% end %></td>
          <td><%= Time.now.strftime("%Y-%d-%m %H:%M:%S %Z") %></td>
          <td><%= page.published %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/pages/modals/_images.html.erb
<div id="images-modal" class="modal fade" data-images-path="<%= admin_images_path(format: :json) %>">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Galerija</h4>
      </div>

      <div class="modal-body">
        Loading images ...
      </div>

    </div>
  </div>
</div>

app/views/admin/pages/modals/_new_image.html.erb
<div id="new-image-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Dodaj sliku</h4>
      </div>

      <div class="modal-body">
        <%= simple_form_for [:admin, Image.new], remote: true do |f| %>
          <%= f.attachinary_file_field :attachment %>

          <%= submit_tag "Koristi sliku", class: "btn btn-primary" %>
          <a class="btn btn-default" data-dismiss="modal">Odustani</a>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/admin/pages/new.html.erb
<% provide(:title, "New Article") %>

<%= render "admin/pages/modals/new_image" %>
<%= render "admin/pages/modals/images" %>

<div class="form-wrapper">
  <h1>New Article</h1>

  <%= simple_form_for [:admin, @page] do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "Create new article", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/blog/about.html.erb
<% provide(:title, "About Me") %>
<div id="about">
  <div class="about-wrapper">
    <div class="grid">
      <div class="unit one-quarter center-on-mobiles">
        <div class="profile">
        <%= image_tag("profile.png", class: "profile-image") %>
        </div>
      </div>
      <div class="unit three-quarters">
        <div class="grid">
          <div class="unit half">
            <div class="name">
              <h1>Matija Ramic</h1>
            </div>
          </div>
          <div class="unit half">
            <div class="description">
              <p>RoR / Web developer</p>
            </div>
          </div>
        </div>
        <div class="grid">
          <div class="unit one-fourth">
            <div class="skills skill-one">
              <%= link_to "", "https://twitter.com/matijaramic", class: "fa fa-twitter fa-2x" %>
            </div>
          </div>
          <div class="unit one-fourth">
            <div class="skills skill-two">
              <%= link_to "", "https://www.linkedin.com/profile/view?id=AAIAABNpgBUBsTvMIF8yJqPaNeZGA4Gndt7mp30&trk=nav_responsive_tab_profile", class: "fa fa-linkedin fa-2x" %>
            </div>
          </div>
          <div class="unit one-fourth">
            <div class="skills skill-three">
              <%= link_to "", "https://www.facebook.com/matija.ramic", class: "fa fa-facebook fa-2x" %>
            </div>
          </div>
          <div class="unit one-fourth">
            <div class="skills skill-four">
              <%= mail_to "matijaramic@gmail.com", "", class: "fa fa-envelope-o fa-2x" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="about-content">
    <p>Lorem ipsum dolor sit amet, at agam alterum ullamcorper his, ea pri velit minim suavitate, adhuc dictas theophrastus eum ne. Cum justo oratio audire ei, mollis commodo persius qui ex, nihil assentior his at. Qui novum appareat ex, quando tacimates delicata cu nec. Odio esse legimus id eum.
    </p>
    <p>Lorem ipsum dolor sit amet, at agam alterum ullamcorper his, ea pri velit minim suavitate, adhuc dictas theophrastus eum ne. Cum justo oratio audire ei, mollis commodo persius qui ex, nihil assentior his at. Qui novum appareat ex, quando tacimates delicata cu nec. Odio esse legimus id eum.
    </p>
    <p>Lorem ipsum dolor sit amet, at agam alterum ullamcorper his, ea pri velit minim suavitate, adhuc dictas theophrastus eum ne. Cum justo oratio audire ei, mollis commodo persius qui ex, nihil assentior his at. Qui novum appareat ex, quando tacimates delicata cu nec. Odio esse legimus id eum.
    </p>
  </div>
</div>

app/views/blog/home.html.erb
<% provide(:title, "Home") %>
<% @pages.each do |page| %>
  <div class="post">
    <div class="post-image">
      <% if false %>
      <% if page.image.present? %>
        <%= page_image_tag(page, :large) %>
      <% else %>
        <%= page_image_tag(page, :no_image) %>
      <% end %>
    <% end %>
    <%= image_tag "profile.png" %>
    </div>
    <div class="entry-blog">
      <h2 class="title"><%= link_to_blog page %></h2>
      <p class="date">Posted on <%= Time.now.strftime("%Y.%d.%m %H:%M") %></p>
    </div>
    <div class="entry-content">
      <div class="grid">
        <div class="unit whole">
          <%= md_to_html page.short_description %>
        </div>
      </div>
      <div class="grid">
        <div class="unit whole">
          <div class="read-more">
            <%= link_to_blog page, text: "Read More" %>
          </div>
        </div>
      </div>
    </div>
    <div class="post-footer">
      <div class="grid">
        <div class="unit half">
          <span class="pull-left">Share</span>
        </div>
        <div class="unit half">
          <ul class="share-buttons pull-right">

            <li><%= link_to "", "https://twitter.com/share?url=#{request.original_url}", title: "Share on Twitter", popup: true, class: "share-btn fa fa-twitter", target: "_blank" %></li>
            <li><%= link_to "", "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}", title: "Share on Facebook", class: "share-btn fa fa-facebook", target: "_blank" %></li>
            <li><%= link_to "", "https://plus.plusgoogle.com/share?url=#{request.original_url}", title: "Share on Google+", class: "fa fa-google-plus", target: "_blank" %></li>
            <li><%= link_to "", "https://www.linkedin.com/shareArticle?mini=true&url=#{request.original_url}", title: "Share on LinkedIn", class: "fa fa-linkedin", target: "_blank" %></li>
            <li><%= mail_to "", "", body: "#{request.original_url}",title: "Send via Email", class: "fa fa-envelope-o" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= will_paginate @pages %>

app/views/blog/show.html.erb
<% provide(:title, @page.title) %>
<div class="post">
  <div class="post-image">
    <% if false %>
      <%= page_image_tag(@page, :large) %>
    <% end %>
    <%= image_tag "profile.png" %>
  </div>
  <div class="entry-blog">
    <h2 class="title"><%= @page.title %></h2>
    <span class="date">Posted on <%= Time.now.strftime("%Y.%d.%m %H:%M") %></span>
  </div>
  <div class="entry-content">
    <div class="grid">
      <div class="unit whole">
        <%= md_to_html @page.body %>
      </div>
    </div>
  </div>
  <div class="post-footer">
    <div class="grid">
      <div class="unit half">
        <span class="pull-left">Share</span>
      </div>
      <div class="unit half">
        <ul class="share-buttons pull-right">

          <li><%= link_to "", "https://twitter.com/share?url=#{request.original_url}", title: "Share on Twitter", popup: true, class: "share-btn fa fa-twitter", target: "_blank" %></li>
          <li><%= link_to "", "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}", title: "Share on Facebook", class: "share-btn fa fa-facebook", target: "_blank" %></li>
          <li><%= link_to "", "https://plus.plusgoogle.com/share?url=#{request.original_url}", title: "Share on Google+", class: "fa fa-google-plus", target: "_blank" %></li>
          <li><%= link_to "", "https://www.linkedin.com/shareArticle?mini=true&url=#{request.original_url}", title: "Share on LinkedIn", class: "fa fa-linkedin", target: "_blank" %></li>
          <li><%= mail_to "", "", body: "#{request.original_url}",title: "Send via Email", class: "fa fa-envelope-o" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="footer-wrapper">
    <ul class="grid">
      <li class="unit one-third">
        <%= link_to image_tag("logo.png", class: "footer-logo"), root_path %>
      </li>
      <li class="unit one-third">
        <p>Copyright © Matija Ramić</p>
      </li>
      <li class="unit one-third">
        <%= link_to "", "", class: "scrollup fa fa-chevron-up fa-2x" %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <%= link_to image_tag("logo.png", class: "logo-mobile"), root_path %>
  <a href="#", id="toggle-nav"></a>
  <div id="nav-container">
    <a href="#", id="close-nav"></a>
  <%= link_to image_tag("logo.png", class: "logo-name"), root_path %>
    <%= render_main_menu %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Admin </title>
    <%= stylesheet_link_tag    'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>
    <%= csrf_meta_tags %>
    <%= cloudinary_js_config %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href='https://fonts.googleapis.com/css?family=Neucha' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <%= render_flash_messages %>
    <%= render 'layouts/admin/header' %>

    <%= yield %>

  </body>
</html>

app/views/layouts/admin/_header.html.erb
<div class="admin-header">
  <%= link_to image_tag("logo.png", class: "admin-logo pull-left"), admin_root_path %>
  <%= render_admin_menu %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href='https://fonts.googleapis.com/css?family=Neucha' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>